"""Renderer-independent EPHI application contracts and command execution."""

from .context import AccessScope, CommandContext, Principal, RevisionVector
from .errors import (
    AggregateNotFoundError,
    AuthorizationError,
    AuthorizationDeniedError,
    CommandError,
    DurableStorageError,
    EffectIdempotencyConflictError,
    InvalidTransitionError,
    IdempotencyConflictError,
    JobNotFoundError,
    JobSemanticConflictError,
    NoEligibleJobError,
    ScopeDeniedError,
    StorageFailureError,
    StaleLeaseError,
    ValidationError,
    ValidationFailureError,
    VersionConflictError,
)
from .hashing import (
    canonical_command_payload_hash,
    canonical_json,
    normalize_domain_payload,
)
from .storage import CommandStorage, CommandUnitOfWork
from .transactions import CommandResult, VersionedAggregateCommandExecutor
from .worker import (
    DEFAULT_HEARTBEAT_INTERVAL,
    DEFAULT_LEASE_DURATION,
    AppliedEffectReceipt,
    JobRecord,
    WorkerJobPort,
    WorkerLease,
    WorkerLeaseConfig,
)

__all__ = [
    "AccessScope",
    "AggregateNotFoundError",
    "AuthorizationError",
    "AuthorizationDeniedError",
    "CommandContext",
    "CommandError",
    "CommandResult",
    "CommandStorage",
    "CommandUnitOfWork",
    "DurableStorageError",
    "EffectIdempotencyConflictError",
    "InvalidTransitionError",
    "IdempotencyConflictError",
    "JobNotFoundError",
    "JobRecord",
    "JobSemanticConflictError",
    "NoEligibleJobError",
    "Principal",
    "RevisionVector",
    "ScopeDeniedError",
    "StorageFailureError",
    "StaleLeaseError",
    "ValidationError",
    "ValidationFailureError",
    "VersionConflictError",
    "VersionedAggregateCommandExecutor",
    "AppliedEffectReceipt",
    "DEFAULT_HEARTBEAT_INTERVAL",
    "DEFAULT_LEASE_DURATION",
    "WorkerJobPort",
    "WorkerLease",
    "WorkerLeaseConfig",
    "canonical_command_payload_hash",
    "canonical_json",
    "normalize_domain_payload",
]
