"""Canonical repository-native EPHI application package."""

from .app import application_identity, self_check
from .application import (
    AccessScope,
    AggregateNotFoundError,
    AuthorizationError,
    AuthorizationDeniedError,
    CommandContext,
    CommandError,
    CommandResult,
    DurableStorageError,
    IdempotencyConflictError,
    Principal,
    RevisionVector,
    ScopeDeniedError,
    StorageFailureError,
    ValidationError,
    ValidationFailureError,
    VersionConflictError,
    VersionedAggregateCommandExecutor,
    canonical_command_payload_hash,
    normalize_domain_payload,
)
from .advisory import (
    AdvisoryEpisode,
    AdvisoryService,
    AttentionProjection,
    EngineeringWorkState,
    TechnicalEpisodeState,
    WorkflowVersionConflict,
)
from .config import RuntimeSettings
from .identity import ApplicationIdentity
from .infrastructure import (
    PostgreSQLReferenceTransactionAdapter,
    PostgresReferenceTransactionAdapter,
    SQLiteReferenceStore,
    SQLiteReferenceTransactionAdapter,
)
from .recovery import (
    CriterionResult,
    IntegrityAttribution,
    ObservationOutcome,
    RecoveryAssessment,
    RecoveryEpisode,
    RecoveryEvaluator,
    RecoveryEligibility,
    RecoveryObservation,
    RecoveryPolicy,
    RecoveryReasonCode,
    RecoveryService,
    RecoveryState,
    RecoveryValidationError,
    Severity,
)
from .value import (
    EventPeriod,
    InMemoryValueRepository,
    MixedCurrencyError,
    SupersessionConflictError,
    SupersessionError,
    UnknownPredecessorError,
    ValueEntry,
    ValueService,
    ValueValidationError,
)

__version__ = ApplicationIdentity.version

__all__ = [
    "ApplicationIdentity",
    "AccessScope",
    "AggregateNotFoundError",
    "AuthorizationError",
    "AdvisoryEpisode",
    "AdvisoryService",
    "AttentionProjection",
    "AuthorizationDeniedError",
    "CommandContext",
    "CommandError",
    "CommandResult",
    "DurableStorageError",
    "CriterionResult",
    "EngineeringWorkState",
    "EventPeriod",
    "IntegrityAttribution",
    "IdempotencyConflictError",
    "InMemoryValueRepository",
    "MixedCurrencyError",
    "ObservationOutcome",
    "Principal",
    "RecoveryAssessment",
    "RecoveryEpisode",
    "RecoveryEvaluator",
    "RecoveryEligibility",
    "RecoveryObservation",
    "RecoveryPolicy",
    "RecoveryReasonCode",
    "RecoveryService",
    "RecoveryState",
    "RecoveryValidationError",
    "RevisionVector",
    "RuntimeSettings",
    "ScopeDeniedError",
    "Severity",
    "SQLiteReferenceStore",
    "SQLiteReferenceTransactionAdapter",
    "PostgreSQLReferenceTransactionAdapter",
    "PostgresReferenceTransactionAdapter",
    "StorageFailureError",
    "TechnicalEpisodeState",
    "SupersessionConflictError",
    "SupersessionError",
    "UnknownPredecessorError",
    "ValueEntry",
    "ValueService",
    "ValueValidationError",
    "ValidationError",
    "ValidationFailureError",
    "VersionConflictError",
    "VersionedAggregateCommandExecutor",
    "WorkflowVersionConflict",
    "application_identity",
    "canonical_command_payload_hash",
    "normalize_domain_payload",
    "self_check",
]
